#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Run from anywhere; values land in the repo-root .env that `npm run server` loads.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
ENV_FILE="$ROOT/.env"

# Install the official Stripe CLI binary into ~/.local/bin. npm -g is the wrong
# tool here: a global prefix of / tries to write /usr/lib/node_modules and fails
# with EACCES. Returns 1 if the human still needs to install it themselves.
install_stripe_cli() {
  if command -v stripe >/dev/null 2>&1; then
    note "Stripe CLI already on PATH: $(command -v stripe)"
    return 0
  fi
  local os arch suffix sums name url tmp
  os="$(uname -s)"
  arch="$(uname -m)"
  case "${os}-${arch}" in
    Linux-x86_64) suffix="linux_x86_64"; sums="stripe-linux-checksums.txt" ;;
    Linux-aarch64|Linux-arm64) suffix="linux_arm64"; sums="stripe-linux-checksums.txt" ;;
    Darwin-x86_64) suffix="mac-os_x86_64"; sums="stripe-mac-checksums.txt" ;;
    Darwin-arm64) suffix="mac-os_arm64"; sums="stripe-mac-checksums.txt" ;;
    *)
      warn "No automatic install for ${os} ${arch}."
      open_url "https://github.com/stripe/stripe-cli/releases/latest"
      step "Download the archive for this computer, unpack it, and put the stripe binary on your PATH."
      return 1
      ;;
  esac
  say "Installing the Stripe CLI into ~/.local/bin. This does not use sudo or npm."
  tmp="$(mktemp -d)"
  url="$(curl -fsSL https://api.github.com/repos/stripe/stripe-cli/releases/latest | grep -oE "https://[^\"]+_${suffix}\\.tar\\.gz" | head -n1 || true)"
  if [[ -z "$url" ]]; then
    warn "Could not find a Stripe CLI download for ${suffix}."
    rm -rf "$tmp"
    return 1
  fi
  name="$(basename "$url")"
  curl -fsSL -o "$tmp/$name" "$url"
  curl -fsSL -o "$tmp/$sums" "https://github.com/stripe/stripe-cli/releases/download/$(basename "$(dirname "$url")")/$sums"
  if ! (cd "$tmp" && grep -E "  ${name}$" "$sums" | sha256sum -c -); then
    warn "Stripe CLI checksum did not match. Nothing was installed."
    rm -rf "$tmp"
    return 1
  fi
  tar -xzf "$tmp/$name" -C "$tmp"
  mkdir -p "$HOME/.local/bin"
  install -m 755 "$tmp/stripe" "$HOME/.local/bin/stripe"
  rm -rf "$tmp"
  export PATH="$HOME/.local/bin:$PATH"
  note "Installed $($HOME/.local/bin/stripe version | head -n1) at $HOME/.local/bin/stripe"
}

# capture KEY PREFIX "Prompt" [secret]
# Keeps asking until the value starts with PREFIX, then writes it to .env.
# A live secret key (sk_live_) is refused unless the human confirms.
capture() {
  local key="$1" prefix="$2" prompt="$3" mode="${4:-}" value=""
  while true; do
    if [[ "$mode" == secret ]]; then
      ask_secret "$key" "$prompt"
    else
      ask "$key" "$prompt"
    fi
    value="${!key}"
    value="${value//[[:space:]]/}"
    if [[ -z "$value" ]]; then
      warn "Paste a value to continue."
      continue
    fi
    if [[ "$prefix" == sk_test_ && "$value" == sk_live_* ]]; then
      warn "That is a live secret key. Sandbox keys start with sk_test_."
      if confirm "Save this live key anyway?"; then
        break
      fi
      continue
    fi
    if [[ "$value" != ${prefix}* ]]; then
      warn "That should start with ${prefix}."
      continue
    fi
    break
  done
  printf -v "$key" '%s' "$value"
  write_env "$key" "$value"
}

banner "Connect Stripe to Groundwork"

# ── 1. Sandbox ─────────────────────────────────────────────────────────────
stage "Stay in the sandbox"
say "Paid plans are created in a Stripe sandbox. The server uses test keys (sk_test_) and price IDs from that same sandbox."
open_url "https://dashboard.stripe.com/test/products"
step "Check the banner at the top: it should say you are testing in a sandbox."
step "The account switcher at the top left should be the sandbox (for example Method LLC sandbox), not the live account."
step "If the banner is gone, switch to the sandbox before you create anything."
pause "Press Enter when the product catalog is open in the sandbox."

# ── 2. Bring your own model, $9/month ──────────────────────────────────────
stage "Price for Bring your own model"
say "This is the byom plan: 9 USD every month. Checkout looks up the price ID, not the product name."
step "On Product catalog, click Create product (top right) or Add a product."
step "Name: Bring your own model"
step "Description (shown at checkout): Use the Claude subscription on this computer, or paste a key from OpenRouter, Anthropic, Google, xAI, or OpenAI."
step "Pricing model: flat rate. Choose Recurring, not one time."
step "Amount 9.00, currency USD, billing period Monthly."
step "Leave tax off unless you already collect Stripe Tax. Save the product."
step "On the product page, under Pricing, open the 9.00 USD monthly price and copy the ID that starts with price_."
capture STRIPE_PRICE_BYOM "price_" "Paste the Bring your own model price ID:"

# ── 3. Groundwork, $20/month ───────────────────────────────────────────────
stage "Price for Groundwork"
say "This is the included plan: 20 USD every month. It needs its own price ID."
open_url "https://dashboard.stripe.com/test/products"
step "Click Create product again."
step "Name: Groundwork"
step "Description: We run the models. 8 dollars of credit a month, smaller model by default."
step "Flat rate, Recurring, amount 20.00, currency USD, billing period Monthly. Save."
step "Open that price and copy its price_ ID. It must be a different ID from the 9 dollar plan."
while true; do
  capture STRIPE_PRICE_INCLUDED "price_" "Paste the Groundwork price ID:"
  if [[ "$STRIPE_PRICE_INCLUDED" != "$STRIPE_PRICE_BYOM" ]]; then
    break
  fi
  warn "That is the same ID as Bring your own model. Open the 20 dollar price and copy its ID."
done

# ── 4. Secret key ──────────────────────────────────────────────────────────
stage "Sandbox secret key"
say "The server creates customers, Checkout sessions, and the billing portal with this key. The publishable key is not used."
open_url "https://dashboard.stripe.com/test/apikeys"
step "Stay in the sandbox. If this page is not API keys, click Developers at the bottom of the left sidebar, then API keys."
step "On the Secret key row, click Reveal test key and copy it. It starts with sk_test_."
capture STRIPE_SECRET_KEY "sk_test_" "Paste the secret key:" secret

# ── 5. Customer portal ─────────────────────────────────────────────────────
stage "Save the customer portal"
say "Manage billing on the site calls the billing portal API. Stripe rejects that call until a portal configuration is saved in this sandbox."
open_url "https://dashboard.stripe.com/test/settings/billing/portal"
step "Stay in the sandbox. The page is Customer portal."
step "Allow customers to update their payment method and to cancel their subscription."
step "Click Save, even if the defaults already look right."
until confirm "Have you clicked Save on the customer portal page?"; do
  say "The Manage billing button fails until that configuration exists."
done

# ── 6. Webhook signing secret ──────────────────────────────────────────────
stage "Webhook signing secret"
say "After checkout, Stripe posts checkout.session.completed, customer.subscription.updated, and customer.subscription.deleted."
say "The server checks the raw body with a snapshot-event signing secret (whsec_). A thin event will not update the plan."
if confirm "Forward events to this computer (local server on port 8787)?"; then
  if ! install_stripe_cli; then
    pause "Press Enter once the stripe command works in a new terminal."
  fi
  say "In a second terminal, log in and start the listener. Leave that terminal running."
  say "  export PATH=\"\$HOME/.local/bin:\$PATH\""
  say "  stripe login"
  say "  stripe listen --events checkout.session.completed,customer.subscription.updated,customer.subscription.deleted --forward-to localhost:8787/v1/stripe/webhook"
  step "Copy the secret from: Ready! Your webhook signing secret is whsec_…"
  note "This secret works only while that stripe listen process is running. 8787 is the default port."
else
  open_url "https://dashboard.stripe.com/test/workbench/webhooks"
  step "Stay in the sandbox. If that URL is not Webhooks, click Developers, then Workbench, then the Webhooks tab."
  step "Click Create an event destination. Choose Account (your own account)."
  step "Select checkout.session.completed, customer.subscription.updated, and customer.subscription.deleted."
  step "Continue, then choose Webhook endpoint. If it asks for a payload, choose snapshot (the full event), not thin."
  step "Endpoint URL: https://<your public host>/v1/stripe/webhook"
  step "After it is created, reveal the signing secret. It starts with whsec_."
  note "Put that same secret on the deployed server. The local stripe listen secret is a different value."
fi
capture STRIPE_WEBHOOK_SECRET "whsec_" "Paste the webhook signing secret:" secret

# ── 7. Confirm ─────────────────────────────────────────────────────────────
stage "Turn billing on"
say "From the repo root, start the server. It loads ${ENV_FILE}."
say "  npm run server"
step "Wait until the log includes: billing on"
step "Open http://127.0.0.1:8787, sign in, and open plans. Bring your own model and Groundwork should start Checkout."
note "Sandbox card: 4242 4242 4242 4242, any future expiry, any CVC. The plan updates only while stripe listen is running, or after the public webhook delivers."
pause "Press Enter when the log says billing on."

finish
